// resources/js/Pages/Domains/Edit.vue
<template>
  <AppLayout>
    <div class="px-4 py-6 sm:px-0">
      <div class="mb-8">
        <h1 class="text-3xl font-bold text-gray-900">Editar Domínio</h1>
        <p class="mt-2 text-sm text-gray-600">Atualizar configuração do domínio e configurações SSL para <span class="font-semibold">{{ domain.name }}</span>.</p>
      </div>

      <Card class="max-w-2xl">
        <form @submit.prevent="submit" class="space-y-6">
          <Input
            id="name"
            v-model="form.name"
            label="Nome do Domínio"
            type="text"
            placeholder="exemplo.com"
            required
            :error="errors.name"
            help="Digite um nome de domínio válido (ex: exemplo.com, api.exemplo.com)"
          />

          <Input
            id="description"
            v-model="form.description"
            label="Descrição"
            type="textarea"
            placeholder="Descrição opcional para este domínio"
            :error="errors.description"
            help="Adicione uma descrição para ajudar a identificar o propósito deste domínio"
            :rows="3"
          />

          <!-- Configurações Básicas -->
          <div class="space-y-4">
            <h3 class="text-lg font-medium text-gray-900">Configurações Básicas</h3>
            
            <div class="flex items-start space-x-3 p-4 bg-green-50 rounded-lg border border-green-200">
              <div class="flex items-center h-5">
                <input
                  id="is_active"
                  v-model="form.is_active"
                  type="checkbox"
                  class="focus:ring-green-500 h-4 w-4 text-green-600 border-gray-300 rounded transition-colors duration-200"
                />
              </div>
              <div class="text-sm">
                <label for="is_active" class="font-medium text-green-900">Domínio Ativo</label>
                <p class="text-green-700">Habilitar este domínio na configuração do proxy</p>
              </div>
            </div>

            <div class="flex items-start space-x-3 p-4 bg-blue-50 rounded-lg border border-blue-200">
              <div class="flex items-center h-5">
                <input
                  id="auto_ssl"
                  v-model="form.auto_ssl"
                  type="checkbox"
                  class="focus:ring-blue-500 h-4 w-4 text-blue-600 border-gray-300 rounded transition-colors duration-200"
                />
              </div>
              <div class="text-sm">
                <label for="auto_ssl" class="font-medium text-blue-900">SSL Automático (Let's Encrypt)</label>
                <p class="text-blue-700">Obter e renovar automaticamente certificados SSL via Let's Encrypt</p>
              </div>
            </div>
          </div>

          <!-- Configurações de Segurança -->
          <div class="space-y-4">
            <h3 class="text-lg font-medium text-gray-900">Configurações de Segurança</h3>
            
            <div class="flex items-start space-x-3 p-4 bg-orange-50 rounded-lg border border-orange-200">
              <div class="flex items-center h-5">
                <input
                  id="force_https"
                  v-model="form.force_https"
                  type="checkbox"
                  class="focus:ring-orange-500 h-4 w-4 text-orange-600 border-gray-300 rounded transition-colors duration-200"
                />
              </div>
              <div class="text-sm">
                <label for="force_https" class="font-medium text-orange-900">Forçar HTTPS</label>
                <p class="text-orange-700">Redirecionar automaticamente HTTP → HTTPS (recomendado)</p>
              </div>
            </div>

            <div class="flex items-start space-x-3 p-4 bg-red-50 rounded-lg border border-red-200">
              <div class="flex items-center h-5">
                <input
                  id="block_external_access"
                  v-model="form.block_external_access"
                  type="checkbox"
                  class="focus:ring-red-500 h-4 w-4 text-red-600 border-gray-300 rounded transition-colors duration-200"
                />
              </div>
              <div class="text-sm">
                <label for="block_external_access" class="font-medium text-red-900">Bloquear Acesso Externo</label>
                <p class="text-red-700">Impedir acesso direto às portas da aplicação (ex: localhost:8484)</p>
              </div>
            </div>

            <div v-if="form.block_external_access" class="ml-7 p-4 bg-gray-50 rounded-lg border border-gray-200">
              <label for="internal_bind_ip" class="block text-sm font-medium text-gray-700 mb-2">
                IP de Bind Interno
              </label>
              <select
                id="internal_bind_ip"
                v-model="form.internal_bind_ip"
                class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500"
              >
                <option value="127.0.0.1">127.0.0.1 (Localhost apenas)</option>
                <option value="0.0.0.0">0.0.0.0 (Todos os IPs)</option>
              </select>
              <p class="mt-1 text-xs text-gray-500">
                127.0.0.1 = Acesso apenas local | 0.0.0.0 = Acesso de qualquer IP
              </p>
            </div>
          </div>

          <!-- Configurações de Redirecionamento -->
          <div class="space-y-4">
            <h3 class="text-lg font-medium text-gray-900">Redirecionamento WWW</h3>
            
            <div class="flex items-start space-x-3 p-4 bg-purple-50 rounded-lg border border-purple-200">
              <div class="flex items-center h-5">
                <input
                  id="www_redirect"
                  v-model="form.www_redirect"
                  type="checkbox"
                  class="focus:ring-purple-500 h-4 w-4 text-purple-600 border-gray-300 rounded transition-colors duration-200"
                />
              </div>
              <div class="text-sm">
                <label for="www_redirect" class="font-medium text-purple-900">Redirecionamento WWW</label>
                <p class="text-purple-700">Redirecionar entre www.dominio.com e dominio.com</p>
              </div>
            </div>

            <div v-if="form.www_redirect" class="ml-7 p-4 bg-gray-50 rounded-lg border border-gray-200">
              <label for="www_redirect_type" class="block text-sm font-medium text-gray-700 mb-2">
                Tipo de Redirecionamento
              </label>
              <select
                id="www_redirect_type"
                v-model="form.www_redirect_type"
                class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500"
              >
                <option value="www_to_non_www">www.dominio.com → dominio.com</option>
                <option value="non_www_to_www">dominio.com → www.dominio.com</option>
              </select>
            </div>
          </div>

          <div class="flex justify-end space-x-3 pt-6 border-t border-gray-200">
            <Button @click="router.visit('/domains')" variant="outline">
              Cancelar
            </Button>
            <Button type="submit" :loading="processing" variant="default">
              Atualizar Domínio
            </Button>
          </div>
        </form>
      </Card>
    </div>
  </AppLayout>
</template>

<script setup>
import { reactive, ref } from 'vue'
import { router } from '@inertiajs/vue3'
import AppLayout from '@/Layouts/AppLayout.vue'
import Card from '@/Components/ui/Card.vue'
import Button from '@/Components/ui/Button.vue'
import Input from '@/Components/Input.vue'

const props = defineProps({
  domain: { type: Object, required: true },
  errors: { type: Object, default: () => ({}) }
})

const form = reactive({
  name: props.domain.name,
  description: props.domain.description || '',
  auto_ssl: props.domain.auto_ssl,
  is_active: props.domain.is_active,
  force_https: props.domain.force_https ?? true,
  block_external_access: props.domain.block_external_access ?? false,
  internal_bind_ip: props.domain.internal_bind_ip || '127.0.0.1',
  www_redirect: props.domain.www_redirect ?? false,
  www_redirect_type: props.domain.www_redirect_type || 'www_to_non_www'
})

const processing = ref(false)

const submit = () => {
  processing.value = true
  router.put(`/domains/${props.domain.id}`, form, {
    onSuccess: () => {
      // Redirecionar para a lista de domínios após sucesso
      router.visit('/domains');
    },
    onError: (errors) => {
      console.error('Erro ao atualizar domínio:', errors);
    },
    onFinish: () => {
      processing.value = false;
    }
  })
}
</script>

// frontend/src/app/domains/[id]/edit/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useRouter, useParams } from 'next/navigation'
import { ArrowLeft, Server, Shield, Globe, Lock } from 'lucide-react'
import { toast } from 'react-hot-toast'
import { MainLayout } from '@/components/layout/main-layout'
import { PageLoading } from '@/components/ui/loading'
import { api } from '@/lib/api'
import { useRequireAuth } from '@/hooks/useAuth'

interface UpdateDomainData {
  name: string
  description?: string
  isActive: boolean
  autoTls: boolean
  forceHttps: boolean
  blockExternalAccess: boolean
  enableWwwRedirect: boolean
  bindIp?: string
}

export default function EditDomainPage() {
  useRequireAuth()
  const router = useRouter()
  const params = useParams()
  const queryClient = useQueryClient()
  const domainId = params.id as string

  const [formData, setFormData] = useState<UpdateDomainData>({
    name: '',
    description: '',
    isActive: true,
    autoTls: true,
    forceHttps: true,
    blockExternalAccess: false,
    enableWwwRedirect: false,
    bindIp: '',
  })

  const { data: domain, isLoading } = useQuery({
    queryKey: ['domain', domainId],
    queryFn: () => api.get(`/domains/${domainId}`).then(res => res.data),
    enabled: !!domainId,
  })

  useEffect(() => {
    if (domain) {
      setFormData({
        name: domain.name || '',
        description: domain.description || '',
        isActive: domain.isActive ?? true,
        autoTls: domain.autoTls ?? true,
        forceHttps: domain.forceHttps ?? true,
        blockExternalAccess: domain.blockExternalAccess ?? false,
        enableWwwRedirect: domain.enableWwwRedirect ?? false,
        bindIp: domain.bindIp || '',
      })
    }
  }, [domain])

  const updateDomainMutation = useMutation({
    mutationFn: (data: UpdateDomainData) => api.patch(`/domains/${domainId}`, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['domains'] })
      queryClient.invalidateQueries({ queryKey: ['domain', domainId] })
      toast.success('Domínio atualizado com sucesso!')
      router.push('/domains')
    },
    onError: (error: any) => {
      toast.error(error.response?.data?.message || 'Erro ao atualizar domínio')
    },
  })

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!formData.name.trim()) {
      toast.error('Nome do domínio é obrigatório')
      return
    }
    updateDomainMutation.mutate(formData)
  }

  const handleBack = () => {
    router.push('/domains')
  }

  if (isLoading) {
    return (
      <MainLayout>
        <PageLoading />
      </MainLayout>
    )
  }

  if (!domain) {
    return (
      <MainLayout>
        <div className="text-center py-12">
          <h2 className="text-xl font-semibold text-foreground">Domínio não encontrado</h2>
          <p className="text-muted-foreground mt-2">O domínio solicitado não foi encontrado.</p>
          <button
            onClick={handleBack}
            className="btn-primary mt-4"
          >
            Voltar para Domínios
          </button>
        </div>
      </MainLayout>
    )
  }

  return (
    <MainLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <button
              onClick={handleBack}
              className="p-2 text-muted-foreground hover:text-foreground transition-colors"
            >
              <ArrowLeft className="h-5 w-5" />
            </button>
            <div>
              <h1 className="text-3xl font-bold text-foreground">
                Editar Domínio
              </h1>
              <p className="text-muted-foreground">
                Edite as configurações do domínio {domain.name}
              </p>
            </div>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Informações Básicas */}
          <div className="card">
            <div className="card-content">
              <div className="flex items-center space-x-2 mb-6">
                <Server className="h-5 w-5 text-blue-500" />
                <h2 className="text-lg font-semibold text-foreground">
                  Informações Básicas
                </h2>
              </div>

              <div className="space-y-4">
                <div>
                  <label htmlFor="name" className="block text-sm font-medium text-foreground mb-2">
                    Nome do Domínio <span className="text-red-500">*</span>
                  </label>
                  <input
                    id="name"
                    type="text"
                    value={formData.name}
                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                    placeholder="exemplo.com"
                    className="input w-full"
                    required
                  />
                  <p className="text-xs text-muted-foreground mt-1">
                    Nome do domínio (ex: exemplo.com, www.exemplo.com)
                  </p>
                </div>

                <div>
                  <label htmlFor="description" className="block text-sm font-medium text-foreground mb-2">
                    Descrição
                  </label>
                  <textarea
                    id="description"
                    value={formData.description}
                    onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                    placeholder="Descrição do domínio e sua finalidade..."
                    rows={3}
                    className="input w-full resize-none"
                  />
                  <p className="text-xs text-muted-foreground mt-1">
                    Descrição opcional para identificar o domínio
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Configurações de Ativação */}
          <div className="card">
            <div className="card-content">
              <div className="flex items-center space-x-2 mb-6">
                <Globe className="h-5 w-5 text-green-500" />
                <h2 className="text-lg font-semibold text-foreground">
                  Configurações de Ativação
                </h2>
              </div>

              <div className="space-y-4">
                <label className="flex items-start space-x-3">
                  <input
                    id="isActive"
                    type="checkbox"
                    checked={formData.isActive}
                    onChange={(e) => setFormData({ ...formData, isActive: e.target.checked })}
                    className="mt-0.5 h-4 w-4 rounded"
                  />
                  <div>
                    <span className="text-sm font-medium text-foreground">
                      Ativar Domínio
                    </span>
                    <p className="text-sm text-muted-foreground">
                      Quando ativo, o domínio ficará disponível para receber tráfego e configurar redirects
                    </p>
                  </div>
                </label>

                <label className="flex items-start space-x-3">
                  <input
                    id="autoTls"
                    type="checkbox"
                    checked={formData.autoTls}
                    onChange={(e) => setFormData({ ...formData, autoTls: e.target.checked })}
                    className="mt-0.5 h-4 w-4 rounded"
                  />
                  <div>
                    <span className="text-sm font-medium text-foreground">
                      SSL Automático (Let&apos;s Encrypt)
                    </span>
                    <p className="text-sm text-muted-foreground">
                      Gerar e renovar automaticamente certificados SSL gratuitos via Let&apos;s Encrypt
                    </p>
                  </div>
                </label>
              </div>
            </div>
          </div>

          {/* Configurações de Segurança */}
          <div className="card">
            <div className="card-content">
              <div className="flex items-center space-x-2 mb-6">
                <Shield className="h-5 w-5 text-red-500" />
                <h2 className="text-lg font-semibold text-foreground">
                  Configurações de Segurança
                </h2>
              </div>

              <div className="space-y-4">
                <label className="flex items-start space-x-3">
                  <input
                    id="forceHttps"
                    type="checkbox"
                    checked={formData.forceHttps}
                    onChange={(e) => setFormData({ ...formData, forceHttps: e.target.checked })}
                    className="mt-0.5 h-4 w-4 rounded"
                  />
                  <div>
                    <span className="text-sm font-medium text-foreground">
                      Forçar HTTPS (Redirecionamento HTTP → HTTPS)
                    </span>
                    <p className="text-sm text-muted-foreground">
                      Redireciona automaticamente todo tráfego HTTP para HTTPS (recomendado)
                    </p>
                  </div>
                </label>

                <label className="flex items-start space-x-3">
                  <input
                    id="blockExternalAccess"
                    type="checkbox"
                    checked={formData.blockExternalAccess}
                    onChange={(e) => setFormData({ ...formData, blockExternalAccess: e.target.checked })}
                    className="mt-0.5 h-4 w-4 rounded"
                  />
                  <div>
                    <span className="text-sm font-medium text-foreground">
                      Bloquear Acesso Externo Direto
                    </span>
                    <p className="text-sm text-muted-foreground">
                      Impede acesso direto às portas da aplicação (ex: localhost:8484) de IPs externos
                    </p>
                  </div>
                </label>
              </div>
            </div>
          </div>

          {/* Redirecionamento WWW */}
          <div className="card">
            <div className="card-content">
              <div className="flex items-center space-x-2 mb-6">
                <Lock className="h-5 w-5 text-purple-500" />
                <h2 className="text-lg font-semibold text-foreground">
                  Redirecionamento WWW
                </h2>
              </div>

              <div className="space-y-4">
                <label className="flex items-start space-x-3">
                  <input
                    id="enableWwwRedirect"
                    type="checkbox"
                    checked={formData.enableWwwRedirect}
                    onChange={(e) => setFormData({ ...formData, enableWwwRedirect: e.target.checked })}
                    className="mt-0.5 h-4 w-4 rounded"
                  />
                  <div>
                    <span className="text-sm font-medium text-foreground">
                      Ativar Redirecionamento WWW
                    </span>
                    <p className="text-sm text-muted-foreground">
                      Redireciona entre www.dominio.com e dominio.com
                    </p>
                  </div>
                </label>
              </div>
            </div>
          </div>

          {/* Botões de Ação */}
          <div className="flex justify-end space-x-4 pt-6 border-t border-border">
            <button
              type="button"
              onClick={handleBack}
              className="btn-secondary"
            >
              Cancelar
            </button>
            <button
              type="submit"
              disabled={updateDomainMutation.isPending}
              className="btn-primary"
            >
              {updateDomainMutation.isPending ? 'Salvando...' : 'Salvar Alterações'}
            </button>
          </div>
        </form>
      </div>
    </MainLayout>
  )
}
